language: objective-c
osx_image: xcode7.3
xcode_workspace: welcome-ios.xcworkspace
xcode_scheme: welcome-ios
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master